# docker-compose.yml
version: '3'
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - database
  database:
    image: mongo:latest
    ports:
      - "27017:27017"