# docker-compose.yml
version: '3'
services:
  web_app:
    container_name: ponyo-feels
    # restart: always
    build: .
    ports:
      - '5001:5001'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  